### ISSUE TITLE
genewise2

### ISSUE THREAD

**Issue by thoelken** [hdetering/discomark#1]
In your wiki, please link to correct version of (gene)wise2 you require (2.4.1) and not the ftp which stopped listing it after version 2.2.

The new link is https://www.ebi.ac.uk/~birney/wise2/

I dug this up because I am reviewing https://github.com/mptrsen/Orthograph and wanted to test both implementations side-by-side.

**Comment by hdetering** [comment]
Just updated the link. Thanks for letting us know.
